global:
  scrape_interval: 10s
  evaluation_interval: 1s

rule_files:
  - life.rules
  - alert.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - demo.robustperception.io:9090
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets:
        - demo.robustperception.io:9091
  - job_name: 'alertmanager'
    static_configs:
      - targets:
        - demo.robustperception.io:9093
  - job_name: 'node'
    static_configs:
      - targets:
{%for host in groups['all'] %}
        - {{host}}:9100
{%endfor%}
